server:
  port: 8080
spring:
  application:
    name: srv-challenge-orcamento
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/srv-challenge-orcamento?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: developer
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect